apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: princewillopah/mern-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-prod
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP












# # backend-deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: princewillopah/mern-backend:latest
#         ports:
#         - containerPort: 5000
#         env:
#         - name: DB_USER
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: mongo-root-username
#         - name: DB_PASS
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: mongo-root-password
#         - name: DB_HOST
#           value: mongodb-service
#         - name: DB_NAME
#           valueFrom:
#             configMapKeyRef:
#               name: mongo-config
#               key: mongo-db
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
# spec:
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000