apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: mern-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:1.0.0-alpha.4
          ports:
            - containerPort: 8000
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo-service
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mern-prod
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP





# # mongo-express-deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongo-express
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mongo-express
#   template:
#     metadata:
#       labels:
#         app: mongo-express
#     spec:
#       containers:
#       - name: mongo-express
#         image: mongo-express
#         env:
#         - name: ME_CONFIG_MONGODB_ADMINUSERNAME
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: mongo-root-username
#         - name: ME_CONFIG_MONGODB_ADMINPASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: mongo-root-password
#         - name: ME_CONFIG_MONGODB_SERVER
#           value: mongodb-service
#         ports:
#         - containerPort: 8081
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-express-service
# spec:
#   selector:
#     app: mongo-express
#   ports:
#     - protocol: TCP
#       port: 8081
#       targetPort: 8081