apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mern-prod
stringData:
  mongo-root-username: admin
  mongo-root-password: supersecurepassword



# # mongo-secret.yaml
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongo-secret
# type: Opaque
# data:
#   mongo-root-username: YWRtaW4=       # admin
#   mongo-root-password: cGFzc3dvcmQ=   # password