architecture: standalone
auth:
  enabled: true
  rootPassword: ""
  username: ""
  password: ""
  database: myappdb
persistence:
  enabled: true
  size: 1Gi
service:
  type: ClusterIP
  port: 27017
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"