apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-frontend-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "react-frontend-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort | default "" }}
  selector:
    {{- include "react-frontend-chart.selectorLabels" . | nindent 4 }}
