# docker-compose.yml
version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    networks:
      - micro-net

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    networks:
      - micro-net

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge