apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-backend-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "node-backend-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "node-backend-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "node-backend-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}




