# docker-compose.yml
services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    networks:
      - micro-net

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    networks:
      - micro-net

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    networks:
      - micro-net

  review-service:
    build: ./review-service
    ports:
      - "5004:5004"
    networks:
      - micro-net

  frontend:
        build: ./frontend
        networks:
          - micro-net

  # docker-compose.yml (append this)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - product-service
      - order-service
      - review-service
    networks:
      - micro-net

 

networks:
  micro-net:
    driver: bridge