version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mern-ecom
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-ecom
      - JWT_SECRET=verysecret_jwt_here
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
