services:
  mongo:
    image: mongo:7.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./netflix-api
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/netflix
    volumes:
      - ./netflix-api:/app
    command: npm start

  frontend:
    build:
      context: ./netflix-ui
    ports:
      - "3000:80"
    volumes:
      - ./netflix-ui:/app
    env_file:
      - ./netflix-ui/.env

volumes:
  mongo_data:
